// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: trace_payload.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TracePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostName     string      `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Env          string      `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	Traces       []*APITrace `protobuf:"bytes,3,rep,name=traces,proto3" json:"traces,omitempty"`
	Transactions []*Span     `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *TracePayload) Reset() {
	*x = TracePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TracePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracePayload) ProtoMessage() {}

func (x *TracePayload) ProtoReflect() protoreflect.Message {
	mi := &file_trace_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracePayload.ProtoReflect.Descriptor instead.
func (*TracePayload) Descriptor() ([]byte, []int) {
	return file_trace_payload_proto_rawDescGZIP(), []int{0}
}

func (x *TracePayload) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *TracePayload) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *TracePayload) GetTraces() []*APITrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *TracePayload) GetTransactions() []*Span {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_trace_payload_proto protoreflect.FileDescriptor

var file_trace_payload_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63, 0x65, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e,
	0x76, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x50, 0x49, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52,
	0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trace_payload_proto_rawDescOnce sync.Once
	file_trace_payload_proto_rawDescData = file_trace_payload_proto_rawDesc
)

func file_trace_payload_proto_rawDescGZIP() []byte {
	file_trace_payload_proto_rawDescOnce.Do(func() {
		file_trace_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_trace_payload_proto_rawDescData)
	})
	return file_trace_payload_proto_rawDescData
}

var file_trace_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trace_payload_proto_goTypes = []interface{}{
	(*TracePayload)(nil), // 0: pb.TracePayload
	(*APITrace)(nil),     // 1: pb.APITrace
	(*Span)(nil),         // 2: pb.Span
}
var file_trace_payload_proto_depIdxs = []int32{
	1, // 0: pb.TracePayload.traces:type_name -> pb.APITrace
	2, // 1: pb.TracePayload.transactions:type_name -> pb.Span
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trace_payload_proto_init() }
func file_trace_payload_proto_init() {
	if File_trace_payload_proto != nil {
		return
	}
	file_trace_proto_init()
	file_span_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_trace_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TracePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trace_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trace_payload_proto_goTypes,
		DependencyIndexes: file_trace_payload_proto_depIdxs,
		MessageInfos:      file_trace_payload_proto_msgTypes,
	}.Build()
	File_trace_payload_proto = out.File
	file_trace_payload_proto_rawDesc = nil
	file_trace_payload_proto_goTypes = nil
	file_trace_payload_proto_depIdxs = nil
}
